version: '2'
services:
  redis:
    image: redis
    command: redis-server
  server:
    #image: ruiramos/typrclub
    build: .
#   volumes:
#    - .:/app
    ports: 
      - "8088:8088"
      - "5088:5088"
    environment:
      - NODE_ENV=production
      - PORT=8088
      - WSPORT=5088
      - REDIS_HOST=redis
